tenant_id: "<TENANT-ID>"
client_id: "<CLIENT-ID>"
client_secret: "<CLIENT-SECRET>"
# client_certificate:
#   thumbprint: "<CERT-THUMBPRINT>"
#   private_key: |
#     -----BEGIN PRIVATE KEY-----
#     ...
#     -----END PRIVATE KEY-----
authority_base: "https://login.microsoftonline.com"
redirect_uri: "https://your-bff-host/#/"
post_logout_redirect_uri: "https://your-bff-host/#/logged-out"
scopes:
  - "openid"
  - "profile"
  - "email"
  - "offline_access"
graph_scopes:
  - "GroupMember.Read.All"
cookie:
  name: "bff_session"
  domain: null
  secure: true
  samesite: "Lax"
  http_only: true
  max_age_minutes: 480
csrf:
  cookie_name: "bff_csrf"
  header_name: "x-csrf-token"
rbac:
  group_to_role:
    business_user:
      - "<MIM-GROUP-ID-1>"
      - "<MIM-GROUP-ID-2>"
    business_admin:
      - "<MIM-GROUP-ID-ADMIN>"
route_policies:
  "/": ["business_user", "business_admin"]
  "/docs": ["business_user", "business_admin"]
  "/scenario": ["business_user", "business_admin"]
  "/chat": ["business_user", "business_admin"]
  "/task": ["business_user", "business_admin"]
  "/dashboard": ["business_admin"]
  "/api/docs": ["business_user", "business_admin"]
  "/api/scenario": ["business_user", "business_admin"]
  "/api/chat": ["business_user", "business_admin"]
  "/api/task": ["business_user", "business_admin"]
  "/api/dashboard": ["business_admin"]
session:
  refresh_skew_seconds: 300
  role_cache_ttl_seconds: 300
cors:
  allowed_origins:
    - "https://your-spa-origin"
